"""empty message

Revision ID: 8caeb88354ef
Revises: 
Create Date: 2018-11-16 19:49:37.483087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8caeb88354ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tagname', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tagname')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('dateJoined', sa.Date(), nullable=False),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('tokens', sa.Text(), nullable=True),
    sa.Column('numOfLogins', sa.Integer(), nullable=True),
    sa.Column('receiveEmail', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_uuid'), 'user', ['uuid'], unique=True)
    op.create_table('challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cid', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('c_tag', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['c_tag'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_cid'), 'challenge', ['cid'], unique=True)
    op.create_index(op.f('ix_challenge_name'), 'challenge', ['name'], unique=False)
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.BigInteger(), nullable=True),
    sa.Column('cid', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('current', sa.Boolean(), nullable=True),
    sa.Column('chal_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chal_status'], ['challenge_status.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cid'], ['challenge.cid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_activity_id'), 'activity', ['activity_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_activity_id'), table_name='activity')
    op.drop_table('activity')
    op.drop_index(op.f('ix_challenge_name'), table_name='challenge')
    op.drop_index(op.f('ix_challenge_cid'), table_name='challenge')
    op.drop_table('challenge')
    op.drop_index(op.f('ix_user_uuid'), table_name='user')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('challenge_status')
    # ### end Alembic commands ###
